import {
  BellRing,
  Bookmark,
  FileText,
  Route,
} from "lucide-react";

import StatCard from "./StatCard";
import { useUserData } from "../../../context/UserDataContext";

function StatsGrid() {
  const {
    routeHistory,
    savedRoutes,
    reports,
    unreadNotifications,
  } = useUserData();

  const stats = [
    {
      title: "Route Searches",
      value: routeHistory.length,
      description: "Routes searched by you",
      icon: Route,
    },
    {
      title: "Saved Routes",
      value: savedRoutes.length,
      description: "Routes in your account",
      icon: Bookmark,
    },
    {
      title: "My Reports",
      value: reports.length,
      description: "Reports generated by you",
      icon: FileText,
    },
    {
      title: "Unread Alerts",
      value: unreadNotifications,
      description: "Notifications needing attention",
      icon: BellRing,
    },
  ];

  return (
    <div className="mt-8 grid gap-6 sm:grid-cols-2 xl:grid-cols-4">
      {stats.map((stat) => (
        <StatCard
          key={stat.title}
          title={stat.title}
          value={stat.value}
          description={stat.description}
          icon={stat.icon}
        />
      ))}
    </div>
  );
}

export default StatsGrid;
